version: "2.2"

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: dbadmin
      POSTGRES_DB: jobSearcher
      POSTGRES_USER: dbadmin
